version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin-root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-students-app:
    image: 714714593268.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    ports:
      - "8787:8787"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin-root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_H2_CONSOLE_ENABLED: true
      SERVER_PORT: 8787
      SPRING_MVC_FORMAT_DATE: d/M/yyyy
    depends_on:
      - postgres

  front-end-angular:
    image: 714714593268.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports:
      - "4200:80"

volumes:
  postgres_data:
