name: Deploy Application

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in directory
        run: ls -l
        
      - name: Set Environment Variables
        run: |
          IMAGE_TAG=${{ github.event.client_payload.image_tag }}
          ENVIRONMENT=${{ github.event.client_payload.environment }}
          echo "Deploying to environment: $ENVIRONMENT"
          echo "Deploying Docker image: $IMAGE_TAG"
        env:
          IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
          ENVIRONMENT: ${{ github.event.client_payload.environment }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: |
          ls -l ./scripts  # List contents of the scripts directory
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh $ENVIRONMENT $IMAGE_TAG
