name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'angular-front/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 714714593268.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=714714593268.dkr.ecr.us-east-1.amazonaws.com/spring-angular:frontend_latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "::set-output name=image_tag::$IMAGE_TAG"
        id: build-and-push

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.build-and-push.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Print Trivy Action Logs
        if: always() # This step runs only if the previous step fails
        run: cat trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Optional: Clean up Docker images
      - name: Clean up Docker images
        if: always()
        run: docker rmi ${{ steps.build-and-push.outputs.image_tag }}